# Generated by Django 6.1 on 2026-08-25 06:17

import student_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdmissionNumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField(unique=True)),
                ('last_number', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='admission_number',
            field=models.CharField(editable=False, max_length=12, unique=True, validators=[student_app.models.validate_admission_number]),
        ),
    ]
