# Generated by Django 6.1 on 2026-08-25 16:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0002_student_profile_image'),
        ('student_app', '0003_student_is_active'),
    ]

    operations = [
    ]
