# Generated by Django 6.1 on 2026-08-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_app', '0004_merge_20260825_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='profile_image',
        ),
    ]
